server:
  port: 9002


grpc:
  client:
    grpc-message-service:
      address: static://localhost:9001
      negotiation-type: TLS
      security:
        trust-cert-collection: file:../../../SSL/client.cert.pem

myApiKey: Ekale6@EkaleMotorihi